### ISSUE TITLE
[MVP] : Incorporate the components from November 1 into code 

### ISSUE THREAD

**Issue by dianephan** [e2nguyen/Watcher#12]
## Description
Incorporate the components from November 1 into code so that we can start bringing the project to life 

## Tasks
- [x] button (requires #21)
- [x] Custom image component (requires #23)
- [ ] Custom div component (hovering over things / the colored sections of the page) (requires #24)
- [ ] Post component (requires #25)
- [ ] Button functionality / tracking (look into Apollo) 
- [ ] Image component functionality / tracking (look into Apollo) 

## QA Notes
- test the components in "light testing" 
- [ ] do the buttons and components show up properly on the local page? 
- [ ] can you click and hover?

## PR
- https://github.com/e2nguyen/Watcher/pull/13
