### ISSUE TITLE
[MVP] : Build Assessment 1 of Main Experience 

### ISSUE THREAD

**Issue by dianephan** [e2nguyen/Watcher#14]
## Description
The first assessment of the game is to have users organically interact with the content on the page. We are emulating a Reddit post or a news headline on social media. 

## Requires
- #24 
- #25 
- #21 

## Tasks
- [ ] Make an eye catching headline for cute themed post 
- [ ] Write random text for cute themed post 

## QA Notes
- [ ] does the text make sense? 
- [ ] does it look convincing enough to be an eye-catching post on reddit or other social media? 
- [ ] does formatting look nice locally?
