### ISSUE TITLE
MVP 

### ISSUE THREAD

**Issue by dianephan** [e2nguyen/Watcher#15]
## Description
Defining the MVP of the project - this is the parent issue that holds the sub tickets for each page we need to build out 

## Tasks
- [ ] Define components to use (requires #12 )
- [ ] Integrate React/JavaScript, React-bootstrap to project directory (requires #1 )
- [ ] Set up simple database using SQLAlchemy (requires #2 )
- [ ] Homepage (requires #19 )
- [ ] Assessment 1 (requires #14 )
- [ ] Assessment 2 (requires #16 )
- [ ] Assessment 3 (requires #17 )
- [ ] Metrics (requires #20 )
- [ ] Informative blurb (requires #22 )
- [ ] Replay/ending (requires #18 )
