### ISSUE TITLE
[MVP] : Build Assessment 2 of Main Experience

### ISSUE THREAD

**Issue by dianephan** [e2nguyen/Watcher#16]
## Description
The first assessment of the game is to have users organically interact with the content on the page. We are emulating a brand account that is posting an ad to promote a product or encourage interaction through ad engagement. 

## Tasks
- [ ] Create ad using Canva 
- [ ] Make up witty username for the OP that posts the ad
- [ ] Write short witty caption 
- [ ] Requires image component (requires #23 )
- [ ] Requires button component (requires #21  )

## QA Notes
- [ ] Is caption believable? 
- [ ] Does the ad look interesting?
