### ISSUE TITLE
[MVP] : Build Assessment 3 of Main Experience

### ISSUE THREAD

**Issue by dianephan** [e2nguyen/Watcher#17]
## Description
The first assessment of the game is to have users organically interact with the content on the page. We are emulating a post about food that would usually be posted on social media - specifically Instagram. 

## Tasks
- [ ] Upload a cool stock photo of food that looks authentic. maybe add filters to it 
- [ ] Make up witty username for the OP that posts the food picture 
- [ ] Write short witty caption that shows off their "uniqueness" and why people should follow them for more food content
- [ ] Requires image component (requires #23 )
- [ ] Requires button component (requires #21  )
