### ISSUE TITLE
[MVP] : Build a replay/ending page 

### ISSUE THREAD

**Issue by dianephan** [e2nguyen/Watcher#18]
## Description
The game is complete! Thank the user for playing the game and encourage them to share it with friends 

## Tasks
- [ ] Figure out how to integrate a "share on [social media site here]" button
- [ ] Use the framework from homepage (requires #19 )
- [ ] OPTIONAL: gif of mascots waving?
