### ISSUE TITLE
[MVP] : Homepage

### ISSUE THREAD

**Issue by dianephan** [e2nguyen/Watcher#19]
## Description
Welcome to the game! Show the users how to start.

## Tasks
- [ ] Build a skeleton as a placeholder 
- [ ] Descriptive short one-liner to introduce people to what they came across
- [ ] Integrate a button that routes to the next page when clicked on
- [ ] Display the 5 cute mascots in circular icon form 
- [ ] Load in the components and other metrics that will be used (even though it's not used in the homepage)
