### ISSUE TITLE
[MVP] : Metrics 

### ISSUE THREAD

**Issue by dianephan** [e2nguyen/Watcher#20]
## Description
A page to display the data that was collected throughout the game from multiple users. We will also show information about the assessment to explain why we did this and what the users did throughout the game.

## Tasks
- [ ] What's the best way to showcase data? 
- [ ] Decide if we want to make an infographic or other things
- [ ] Refer to data collected from (requires #2 )
- [ ] Use the framework from homepage (requires #19 )
