### ISSUE TITLE
[MVP]: Custom Button Component

### ISSUE THREAD

**Issue by e2nguyen** [e2nguyen/Watcher#21]
## Description
A big part of the user experience will involve clicking buttons modeled after those found on social media platforms. In this ticket, we will implement a bare-bones custom button component that does the following: takes in a png asset, ~~**allows for tracking**~~, takes in color properties, and makes takes in text from the children property.

Note: 
- When naming files, and working this react in general, follow PascalCase.
- Let's implement the solution with a functional component based approach 

## Branches
- dianebutton

## Requires
- #26 
- #28 

## Potential solutions
Currently awaiting the SAS integration from #28 in order to prevent confusion and trouble of importing a CSS file to test things out. Since the button requires uploading an image or altering the colors and size, we will need to figure out how to properly build out the component while following the SAS rules. 

For the time being, the button has an `onClick` function that works. The `ButtonProperties` include `React.ReactNode` for the children and can take in any value string to display text on a button. 

Update January 10, 2021: 
We found it too difficult and time consuming to use SAS or Emotion libraries so we plan on trying out the Styled JSX library. It looks a bit too messy for our preference but due to the scope of our project, we decided to try it out to move on towards another part of the project. 

## Tasks
~~- [ ] implement a tracking method (later when we figure out how to store tracking)~~
- [x] create an onClick function to make the button clickable 
- [x] add text inside the button
- [x] add the option to import a picture for the button 
- [x] add dynamic styling where i can pass in a height and width (avatar icons should be 200px each width and height)

## PR
- https://github.com/e2nguyen/Watcher/pull/30
