### ISSUE TITLE
[MVP]: Page with extra information 

### ISSUE THREAD

**Issue by dianephan** [e2nguyen/Watcher#22]
## Description
Woohoo! The game is complete - this page is dedicated to official resources to learn more about our project. We hope to show nontechnical teammates what engineers are capable of coding up and how this can help them define goals/features with engineers better. 

## Tasks
- [ ] List at least 3 official sources (research papers, articles, etc) 
- [ ] Write a nice ending message for people who made it this far
- [ ] Use the framework from homepage (requires #19 )
