### ISSUE TITLE
[MVP]: Custom div component (the colored sections of the page)

### ISSUE THREAD

**Issue by e2nguyen** [e2nguyen/Watcher#24]
## Description
We need to be able to track how long a user spends on a given portion of the page, so we'll have to create a custom div component that tracks time spent.

## Branches
custom_div_component_24

## Requires
- #26 

## Tasks
- [x] the UI side
- [x] create the main experience page (page with 3 divs) 
- [x] include placeholder text in the experiences 
- [x] create a `wrapper classname="xxx"` (refer to to the dummy code in google docs) 

## PR
#36

**Comment by dianephan** [comment]
@e2nguyen ready for review! created `/main-experience` page so that you can see all 3 divs on a page 
making notes to the issue as well in regards to Apollo 

Here's what `/main-experience` page should look like
<img width="1174" alt="Screen Shot 2021-02-06 at 11 17 00 AM" src="https://user-images.githubusercontent.com/17483220/107127740-01737580-686d-11eb-90de-2e6675bd4519.png">

**Comment by e2nguyen** [comment]
@dianephan, lgtm!
