### ISSUE TITLE
[MVP]: Create Custom Post Component

### ISSUE THREAD

**Issue by e2nguyen** [e2nguyen/Watcher#25]
## Description
We want to create posts that mimick those found on social media platforms, so we'll go ahead and create a custom component using our custom image component and custom button component, along with a user avatar icon (blank default image for now), and some text.

## Requires
- #26 
- #21 
- #23 

## Tasks
- [x] Headline/ caption component (requires #34)
- [x] Avatar/ poster component (requires #37)
- [x] Social media button components 
    - [x] Buttons container (requires #45)
        - [x] like/heart button (requires #41)
        - [x] comment (create a little text input below the post for the user to type in text) (requires #41)
        - [x] share (requires #42)
        - [x] flag (save/bookmark) (requires #42) 
- [x] Reddit based component (requires #47 )
- [x] Facebook based component (requires #48 )
- [ ] API ( requires #53 )
