### ISSUE TITLE
[MVP]: Style integrations

### ISSUE THREAD

**Issue by e2nguyen** [e2nguyen/Watcher#28]
## Description
Using @emotion/styled and @emotion/react.
Reference: https://emotion.sh/docs/typescript

#### Option 1
- In order to integrate styles in a clean manner, let's integrate ` typed-scss-modules` from https://www.npmjs.com/package/typed-scss-modules to our project.

- Source: https://skovy.dev/generating-typescript-definitions-for-css-modules-using-sass/

- Problem: However there's not enough documentation for SASS/SCSS for us right now 

#### Option 2:
- use csstype
- https://github.com/frenic/csstype#readme

#### Option 3: SOLUTION
- use emotion https://emotion.sh/docs/typescript

## Tasks
- [x] ~~install package with `npm i typed-scss-modules`~~
- [x]  install emotion react using `npm install --save @emotion/react`
- [x] install emotion styled using `npm install --save @emotion/styled`
