### ISSUE TITLE
[MVP]: Create Headline Component

### ISSUE THREAD

**Issue by e2nguyen** [e2nguyen/Watcher#34]
## Description
In order to create our app's post component, we need to create a couple subcomponents, one being the headline component that mimics the headlines found in a typical reddit post. Headline component should just be a thin wrapper component.

## Branches
- create_headline_component_34

## Tasks
- [x] should take in the following props:
   - [x] children (do not make optional, otherwise it makes this component useless)
- [x] should be a div that just renders children

## PR
- https://github.com/e2nguyen/Watcher/pull/35

**Comment by e2nguyen** [comment]
@dianephan, this is ready for review. I made some updates to the existing button component additionally since I realized buttons don't necessarily always need children, and the editor was complaining when I altered the syntax for instantiating the button in the playground. Also, lmk if you have any qs about the styling in the headline component.

**Comment by dianephan** [comment]
hi @e2nguyen ! I just tested this branch out on my local machine and everything lgtm! I realized I should have refactored the Button component to match your image component 😅 woops - thanks for doing that though! 

I was surprised we needed a Headline component but it looks pretty straight forward so we can just merge.
