### ISSUE TITLE
[MVP]: Create Avatar component

### ISSUE THREAD

**Issue by e2nguyen** [e2nguyen/Watcher#37]
## Description
As part of creating the post component, we also need to create an avatar component that mimics what is typically seen on instagram or twitter. 
This component is composed of a round avatar that is left aligned followed by a name.

## Branches
- create_avatar_component_37

## Requires
- #23 
- #24

## Potential solutions

Look into flexbox and combine it with bootstrap.

## Tasks
- [x] Use the custom image component for the avatar
- [x] for the time being, just hardcode in a character png from our image library
- [x] wrap the component in the custom div we created

## QA Notes
Inspecting the `AvatarComponent:
![image](https://user-images.githubusercontent.com/17483220/109364228-28591200-7843-11eb-9121-8a7c41b5b090.png)

Project structure when inspecting: 
![image](https://user-images.githubusercontent.com/17483220/109364263-3d35a580-7843-11eb-8b08-550e9faaf660.png)

## PR
#38

**Comment by e2nguyen** [comment]
@dianephan, left one small comment

**Comment by e2nguyen** [comment]
bumped up to 5 because of the time we spent pairing
