### ISSUE TITLE
[MVP]: Create like and comment social media buttons

### ISSUE THREAD

**Issue by e2nguyen** [e2nguyen/Watcher#41]
## Description
We need social media buttons on our post component. This ticket addresses creating the like and comment buttons. To test this visually, let's use the playground.

## Branches
-  `create_like_and_comment_buttons_41`

## Requires
#21
#39

## Tasks
- [x] create a like button that:
   - [x] console logs 'liked' when clicked
   - [x] uses the like png
- [x] create a comment button that:
   - [x]  console logs 'commented' when clicked
   - [x] uses the comment png

## QA Notes
1. Make sure your local app is running with `npm run dev`
2.  Go to the playground at http://localhost:3000/components-playground
3.  Verify that the buttons are at 18px
4. Verify that when the like button is clicked, the console logs "liked"
5. Verify that when the comment button is clicked, the console logs "commented"

## PR
https://github.com/e2nguyen/Watcher/pull/43

**Comment by e2nguyen** [comment]
@dianephan, hey diane this is ready for review

**Comment by dianephan** [comment]
lgtm!!!
