### ISSUE TITLE
[MVP]: Create the share and bookmark social media buttons

### ISSUE THREAD

**Issue by e2nguyen** [e2nguyen/Watcher#42]
## Description
We need social media buttons on our post component. This ticket addresses creating the share and bookmark buttons. To test this visually, let's use the playground.

## Branches
- `share_bookmark_button_42`

## Requires
#21
#39

## Tasks
- [x] create a share button that:
   - [x] console logs 'shared' when clicked
   - [x] uses the share png
- [x] create a bookmark button that:
   - [x]  console logs 'bookmarked' when clicked
   - [x] uses the bookmark png

## QA Notes
1. Make sure your local app is running with `npm run dev`
2.  Go to the playground at http://localhost:3000/components-playground
3.  Verify that the buttons are at 18px
4. Verify that when the like share is clicked, the console logs "you are sharing something"
5. Verify that when the bookmark button is clicked, the console logs "you are bookmarking something"

## PR
#44

**Comment by dianephan** [comment]
lgtm!!!

**Comment by e2nguyen** [comment]
@dianephan, lgtm :fire:
