### ISSUE TITLE
[MVP]: Backend Parent

### ISSUE THREAD

**Issue by e2nguyen** [e2nguyen/Watcher#53]
## Description
This ticket is to keep track of generating the backend of our app.

## Tasks
- [ ]  GraphQL
   - [ ] Install GraphQL ( requires #57 )
   - [ ] Set Up GraphQL Infrastructure (8-13) Query/Mutation ( requires #66 )
   - Mutations:
   - [ ] Create CreateLike Mutation
   - [ ] Create CreateShare Mutation
   - [ ] Create CreateBookmark Mutation
   - [ ] Create CreateUserMetrics Mutation
   - [ ] Create UpdateUserMetrics Mutation (
   - [ ] Create UpdateMetrics Mutation (admin create)
   - [ ] Create CreatePost Mutation (not mvp/ admin)
   - [ ] Create CreateUser Mutaaion (not mvp/ admin)
   - Queries:
   - [ ] Create GetPost Query (admin create)
   - [ ] Create GetLikes Query
   - [ ] Create GetBookmark Query
   - [ ] Create GetUserMetrics Query
   - [ ] Create GetMetrics
- [ ] Write test cases before integrating to whole project ( requires #68 ) 
- [ ] Database
   - [ ] Set up database 
   - [ ] Set up tables (depends on the set up db ticket)
      - [ ] Posts Table -> set up s3 bucket for images, have a column with link to image
      - [ ] User Tables
      - [ ] Likes
      - [ ] Shares
      - [ ] Bookmark
      - [ ] UserMetrics (metrics per user)
      - [ ] OverallMetrics (contains num of likes, shares, bookmarks are any given moment)

- Querying:
   - pull posts
   - pull metrics (likes, clicks, time spent on any particular post)

- Mutation
   - updating metrics:
   - creating likes, clicks, etc
