### ISSUE TITLE
[MVP]: Migrate from styled-jsx to Tailwind CSS

### ISSUE THREAD

**Issue by dianephan** [e2nguyen/Watcher#56]
## Description
Now that we decided to move over to Tailwind CSS, we need to refactor and remove all styled-jsx from the project. 

## Requires
#54 

## Tasks
- [x] migrate avatar component (requires #58)
- [x] migrate social media post components (requires #59)
- [x] migrate button (requires #62)
- [x] migrate image component (requires #59 )
- [x] migrate div, headline, socialmediabuttonscontainer (requires #64)
