### ISSUE TITLE
[MVP]: Install GraphQL 

### ISSUE THREAD

**Issue by dianephan** [e2nguyen/Watcher#57]
## Description
Spend some time installing and setting up GraphQL together. The tech stack is Python and GraphQL
refer to July 18, 2021 - September 12, 2021 for additional resources to set up graphQL and other issues encountered 

## Branches
`install_graphql_57`

## Potential solutions
Writing the query: 
- casing matters 
- use apollo devtools or the sandbox as source of truth to determine what the query needs to look like. this should match the query on the client side (index.tsx) 

Setting up the Apollo Server and ensuring the data shows up: 
- The `resolvers` and `typeDefs` objects must be camelCase 
 
Client
- establishing the URI
- add 
```
const { url } = await server.listen({ port: 4000 })
console.log(`this server is running at the following URL: ${url}`);
```

## Tasks
- [x] install GraphQL packages
   - [x] [Apollo Client](https://www.apollographql.com/docs/react/get-started/)
   - [x] [Apollo Server](https://www.apollographql.com/docs/apollo-server/getting-started/) - how you define the shape of your data and how to fetch it
- [x] install apollo dev tools chrome extension

## PR
#70
