### ISSUE TITLE
[MVP]: Migrate Button Styling to Tailwind CSS

### ISSUE THREAD

**Issue by dianephan** [e2nguyen/Watcher#62]
## Description
Let's migrate the components incrementally from styled jsx to tailwind css. This ticket handles migrating the button component.

## Branches
- `button_styling_migration_62`

## Requires
#58 

## Potential solutions
- bumped this from 3 to 5 because we spent some time understanding how tailwind deals with custom defined height/widths

## Tasks
- [x] migrate button component to tailwind
- [x] migrate like button
- [x] migrate comment button
- [x] migrate share button
- [x] migrate bookmark button

## QA Notes
- Please QA on your end, and verify the social media buttons show when you run the playground locally on your environment
- verify they look like this, and verify the dimensions read 17.99x17.99 when you hover each button

![image](https://user-images.githubusercontent.com/29549301/120939260-100f5380-c6cc-11eb-9933-96a159d8f2b9.png)

## PR
- https://github.com/e2nguyen/Watcher/pull/63

**Comment by e2nguyen** [comment]
@dianephan, please QA this and look over the code when you get the chance -- thanks!

**Comment by dianephan** [comment]
![image](https://user-images.githubusercontent.com/17483220/121646973-b8197980-ca4a-11eb-8585-7d4d3b2812b3.png)

the dimensions rounded up to 18!

**Comment by dianephan** [comment]
read all of the descriptive commit messages and looked over the code. everything works on my end so PRESS THE BUTTON! 👯
