### ISSUE TITLE
[MVP] :  Migrate div, headline, socialmediabuttonscontainer

### ISSUE THREAD

**Issue by dianephan** [e2nguyen/Watcher#64]
## Description
Let's migrate the components incrementally from styled jsx to tailwind css. This ticket handles migrating the div, headline, socialmediabuttonscontainer tsx files.

## Branches
` migrate_remaining_components_to_tailwind_64`

## Requires
#56 

## Tasks
- [x] migrate CustomDiv.tsx
- [x] migrated Headline.tsx
- [x] migrate SocialMediaButtonsContainer.tsx

## PR
#65
