### ISSUE TITLE
[MVP]: Build GraphQL infrastructure to mutate and store data

### ISSUE THREAD

**Issue by dianephan** [e2nguyen/Watcher#66]
## Description
Use Python and GraphQL to make query/mutation/endpoints in the infrastructure for the data before integrating to our project.

## Requires
#57 

## Tasks
   - Create endpoints
   - [ ] define endpoints on frontend before moving to backend ( #69 ) 
   - Mutations:
   - [ ] Create CreateLike Mutation
   - [ ] Create CreateShare Mutation
   - [ ] Create CreateBookmark Mutation
   - [ ] Create CreateUserMetrics Mutation
   - [ ] Create UpdateUserMetrics Mutation (
   - [ ] Create UpdateMetrics Mutation (admin create)
   - [ ] Create CreatePost Mutation (not mvp/ admin)
   - [ ] Create CreateUser Mutaaion (not mvp/ admin)
   - Queries:
   - [ ] Create GetPost Query (admin create)
   - [ ] Create GetLikes Query
   - [ ] Create GetBookmark Query
   - [ ] Create GetUserMetrics Query
   - [ ] Create GetMetrics
