### ISSUE TITLE
[MVP] : Set up FaunaDB 

### ISSUE THREAD

**Issue by dianephan** [e2nguyen/Watcher#71]
## Description
Set up FaunaDB and make sure we can query from our FaunaDB in our application 
 
## Branches
`set_up_database_2`

## Potential solutions
- ended up having to make the apolloclient's URI set to the faunadb URI **WITH** region `us` included
- had to move the apolloClient into the apolloWrapper, otherwise the client was never being initialized and by the time we initialized the provider, no apolloClient could be recognized
   - this involved removing the client file entirely 
- upgraded our packages to support faunadb
- created a schema file to upload to fauadb which defines the possible query/mutation types
  - this is subject to change  
- temporarily exposed our bearer token to test that db connection works, will remove this token in the future and add security around future tokens (with vercel or other equivalent)

## Tasks
- [x] npm install fauna packages (version 4.4.1) 
- [x] set up faunaDB connection 
- [x] make queries to faunaDB from our application 

## PR
#72

**Comment by e2nguyen** [comment]
Upping this to a 13 considering how many issues we ran into

**Comment by e2nguyen** [comment]
@dianephan, we forgot to close this, so doing that now
