### ISSUE TITLE
[MVP]: Hook up Application to vercel

### ISSUE THREAD

**Issue by e2nguyen** [e2nguyen/Watcher#73]
## Description
In order to hide our environment keys/variables, let set up deployments with vercel so we can forgo storing this info in our codebase.

## Tasks
- [x] create new gmail
- [x] create vercel account
- [x] set up @dianephan cli project
- [x] set up @e2nguyen cli project

**Comment by e2nguyen** [comment]
created to document installation, closing since it's done
