### ISSUE TITLE
[MVP]: fix icon styling

### ISSUE THREAD

**Issue by dianephan** [e2nguyen/Watcher#75]
## Description
icon styling is off for some reason (probably before integrating faunadb and vercel)
![image](https://user-images.githubusercontent.com/17483220/147417496-b2b96cec-8a19-4c07-ae02-f95470992917.png)

## Branches
- og: `fix_icon_styling_75`
- new: `fix_tailwind_75`

## Tasks
- [x] upgrade to tailwind 3
- [x] removed unused style packages
   - [x] styled jsx
   - [x] emotion 
- [x] upgrade to at least typescript 4.3.2
## QA Notes
- verify styles work on the playground + main experience

## PR
- https://github.com/e2nguyen/Watcher/pull/new/fix_tailwind_75
