### ISSUE TITLE
[MVP] : update vercel environment variables 

### ISSUE THREAD

**Issue by dianephan** [e2nguyen/Watcher#78]
## Description
update the project's environment variables with key from new faunadb account. 

## Branches
`update_vercel_env_78`

## Tasks
- [x] create new fauna db account for the project
- [x] built a new schema
- [x] add to gitignore

## PR
#79
